# Generated by Django 3.1 on 2020-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(to='TrainingApp.Dish'),
        ),
    ]
