# Generated by Django 3.1 on 2020-08-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingApp', '0003_auto_20200826_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='dish_served',
            new_name='dishes_served',
        ),
    ]
